export { Home } from './Home/Home'
export { Category } from './Category/Category'
export { Rules } from './Rules/Rules'
export { Login } from './Authentication/Login'
export { Signup } from './Authentication/Signup'
export { Question } from './Question/Question'
export { Result } from './Result/Result'
